# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    # ports:
    #   # <Port exposed> : <MySQL Port running inside container>
    #   - '3306:3306'
    expose:
      - '3306'  
    # (this is just an example, not intended to be a production configuration)

